#!/usr/bin/env bash
# Exposes the frontend and backend via Cloudflare quick tunnels (no account
# needed) instead of relying on LAN reachability — use this when local
# network testing (scripts/dev-up.sh) keeps failing: unstable DHCP, a
# router isolating your phone from your Mac, macOS's Local Network
# permission, etc. A tunnel sidesteps all of that by making an *outbound*
# connection from this machine instead of requiring anything to reach it.
#
# Known limitation: LiveKit screen-share media (UDP) is not tunneled by
# this script — online-mode room creation/joining/chat/annotations work
# through the tunnel, but actual screen-share video may not arrive. If you
# need that over a tunnel too, ask for it specifically; it needs LiveKit's
# TCP-fallback path tunneled as well, which this script doesn't set up yet.
set -euo pipefail
cd "$(dirname "$0")/.."

# The frontend is a separate repository now (together-fe). This assumes the
# usual side-by-side checkout; override if yours lives elsewhere:
#   FRONTEND_DIR=~/code/together-fe ./scripts/tunnel-up.sh
FRONTEND_DIR="${FRONTEND_DIR:-../frontend}"
if [ ! -d "$FRONTEND_DIR" ]; then
  echo "Frontend checkout not found at $FRONTEND_DIR." >&2
  echo "Set FRONTEND_DIR to your together-fe checkout and re-run." >&2
  exit 1
fi

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared not found — install it with: brew install cloudflared" >&2
  exit 1
fi

mkdir -p /tmp/together-tunnels
BACKEND_LOG=/tmp/together-tunnels/backend.log
FRONTEND_LOG=/tmp/together-tunnels/frontend.log

# Kill any tunnels from a previous run of this script.
pkill -f "cloudflared tunnel --url http://localhost:8080" 2>/dev/null || true
pkill -f "cloudflared tunnel --url http://localhost:3001" 2>/dev/null || true
sleep 1

echo "Starting backend tunnel (localhost:8080)..."
: > "$BACKEND_LOG"
cloudflared tunnel --url http://localhost:8080 > "$BACKEND_LOG" 2>&1 &

echo "Starting frontend tunnel (localhost:3001)..."
: > "$FRONTEND_LOG"
cloudflared tunnel --url http://localhost:3001 > "$FRONTEND_LOG" 2>&1 &

wait_for_url() {
  local log="$1"
  for _ in $(seq 1 30); do
    url="$(grep -o 'https://[a-zA-Z0-9-]*\.trycloudflare\.com' "$log" | head -1 || true)"
    if [ -n "$url" ]; then
      echo "$url"
      return 0
    fi
    sleep 1
  done
  echo "" # timed out
}

BACKEND_URL="$(wait_for_url "$BACKEND_LOG")"
FRONTEND_URL="$(wait_for_url "$FRONTEND_LOG")"

if [ -z "$BACKEND_URL" ] || [ -z "$FRONTEND_URL" ]; then
  echo "Tunnel(s) didn't come up in time — check $BACKEND_LOG / $FRONTEND_LOG" >&2
  exit 1
fi

echo "Backend tunnel:  $BACKEND_URL"
echo "Frontend tunnel: $FRONTEND_URL"

# Wire the frontend at the backend's tunnel URL — same-origin auto-detection
# (lib/api/client.ts) assumes "same host, port 8080", which is wrong once
# each service has its own distinct tunnel hostname.
cat > "$FRONTEND_DIR/.env.local" <<EOF
# Regenerated by scripts/tunnel-up.sh — don't hand-edit, re-run the script
# after restarting tunnels instead (the URLs change every run).
NEXT_PUBLIC_API_BASE=$BACKEND_URL
NEXT_DEV_ALLOWED_ORIGIN=${FRONTEND_URL#https://}
EOF

# Wire the backend's CORS allowlist to accept the frontend's tunnel origin,
# leaving every other key in .env (LAN_IP, LiveKit Cloud creds) untouched.
# shellcheck source=scripts/env-upsert.sh
. "$(dirname "$0")/env-upsert.sh"
env_upsert TUNNEL_FRONTEND_ORIGIN "$FRONTEND_URL"

echo ""
echo "Restarting backend to pick up the new CORS origin..."
docker compose up -d --build backend

echo ""
echo "Now restart the frontend so it picks up $FRONTEND_DIR/.env.local:"
echo "  (Ctrl-C the running npm run dev, then) cd frontend && npm run dev"
echo ""
echo "Then open this on your phone (any network, not just the same Wi-Fi):"
echo "  $FRONTEND_URL"
